#version: '3.8'

networks:
  nut:
    name: nut
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.0.0/16

services:
  upsdrvctl:
    image: mjast/nutgalaxy5500:1.0
    container_name: upsdrvctl
    networks:
      nut:
        ipv4_address: 172.16.0.2
    environment:
      - TZ={{ TZ }}
    volumes:
      - ups:/var/state/ups
      - ./ups_config:/app/config/etc
    command: ./sbin/upsdrvctl -FF start
    restart: unless-stopped

  upsd:
    image: mjast/nutgalaxy5500:1.0
    container_name: upsd
    networks:
      nut:
        ipv4_address: 172.16.0.3
    environment:
      - TZ={{ TZ }}
    volumes:
      - ups:/var/state/ups
      - ./ups_config:/app/config/etc
    ports:
      - 3493:3493
    command: ./sbin/upsd -FF
    depends_on:
      - upsdrvctl
    restart: unless-stopped

  nginx-proxy:
    image: nginxproxy/nginx-proxy:1.5
    container_name: nginx-proxy
    networks:
      nut:
        ipv4_address: 172.16.0.4
    ports:
      - 80:80
    environment:
      - TZ={{ TZ }}
      - DEFAULT_HOST={{ DEFAULT_HOST }}
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./default_location:/etc/nginx/vhost.d/default_location
      - /etc/nginx/certs:/etc/nginx/certs
      - ./static:/var/www/html/static
    restart: always

  gnut:
    image: mjast/gnut:0.33
    container_name: gnut
    networks:
      nut:
        ipv4_address: 172.16.0.5
    env_file:
      - ./.env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./db_data:/app/db_data
      - ./ups_config:/app/ups_config

volumes:
  ups: